llm = "chatgpt"

[chatgpt]
openai_api_key = "your-api-key-here"
model = "gpt-4-turbo"
system_prompt = "You are an AI assistant that specializes in programming and software development."

[key_bindings]
show_help = '?'
show_history = 'h'
new_chat = 'n'
stop_stream = 't'
load_voice = 'v'

[tts]
url = "http://0.0.0.0:8000/v1/audio/speech"
