---
on:
  push:
    branches:
      - "*"
    tags:
      - "!*"
name: CI
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/install-action@just

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy rustfmt

      - name: Run linting
        run: just lint

      - name: Run debug builds
        run: just build
